In [ ]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [ ]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
# embedding takes  input also as intyeger encoded
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))
# embedding layer needs three inputs = vocab lenght = 17,
# output dimension=2, which means I want to represnt each word as 2 dimensional vector
#  input_length = no. of words

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences)
print(pred)
# now for eachdoc we get new dense vector using embedding

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[[ 0.00866596 -0.04573646]
  [ 0.01989588 -0.00084477]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]]

 [[ 0.01989588 -0.00084477]
  [ 0.01989588 -0.00084477]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]]

 [[ 0.00590213 -0.03061824]
  [ 0.00590213 -0.03061824]
  [-0.03766024  0.00075892]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]]

 [[ 0.02946797  0.03088628]
  [ 0.00532486 -0.02684638]
  [ 0.02946797  0.03088628]
  [ 0.01989588 -0.00084477]
  [ 0.02946797  0.03088628]]

 [[-0.01397891 -0.03488945]
  [ 0.02870988  0.04403055]
  [-0.01946172  0.01235279]
  [-0.03871388 -0.01066488]
  [ 0.00267097 -0.04116853]]

 [[-0.02158823 -0.01941378]
  [-0.02158823 -0.01941378]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853]]

 [[-0.0159352  -0.01966423]
  [-0.0159352  -0.01966423]
  [ 0.00267097 -0.04116853]
  [ 0.00267097 -0.04116853

In [ ]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model = Sequential()
model.add(Embedding(10000, 2))
# voab length is 10000
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - acc: 0.5134 - loss: 0.6920 - val_acc: 0.6394 - val_loss: 0.6277
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.7631 - loss: 0.4902 - val_acc: 0.7997 - val_loss: 0.4364
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - acc: 0.8429 - loss: 0.3689 - val_acc: 0.7897 - val_loss: 0.4582
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8653 - loss: 0.3264 - val_acc: 0.7897 - val_loss: 0.4896
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - acc: 0.8890 - loss: 0.2795 - val_acc: 0.7680 - val_loss: 0.5291


In [ ]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 63,461 (247.90 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 42,308 (165.27 KB)

In [ ]:
# prompt: get the sentiments now using this model , I user can give  input and it should tell me the sentiment , use embeddings to dense the vector to 2 dimensions to convert he text and use rrn model to predict (simple rrn , which I used

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding

# The previous code defined a model, but it was trained on the imdb dataset
# for sentiment analysis. We will use that trained model.

# The tokenizer and padding from the first part are not relevant here as
# we are using the imdb dataset's preprocessing which is handled by
# imdb.load_data().

# The model from the previous code is suitable for sentiment analysis.
# We will use the second model definition which was trained on the imdb dataset.
model = Sequential()
model.add(Embedding(10000, 2))
# voab length is 10000
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

# Compile the model again (it was compiled in the previous code)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# Assume the model has already been trained with the previous code's fit() call.
# If you need to re-train, uncomment the following lines:
# (X_train, y_train), (X_test, y_test) = imdb.load_data()
# X_train = pad_sequences(X_train, padding='post', maxlen=50)
# X_test = pad_sequences(X_test, padding='post', maxlen=50)
# history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))


# Now, let's create a function to take user input and predict sentiment.
# We need to use the same tokenizer/vocabulary as the IMDB dataset.
# The imdb.load_data() function provides the word index mapping.
imdb_word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in imdb_word_index.items()])

def decode_review(text):
  return ' '.join([reverse_word_index.get(i - 3, '?') for i in text])

# Need to map user input text to sequences using the imdb vocabulary
def encode_text(text, word_index, maxlen=50):
  words = text.lower().split()
  encoded = [word_index.get(word, 2) + 3 for word in words] # +3 because 0, 1, 2 are reserved
  padded = pad_sequences([encoded], padding='post', maxlen=maxlen)
  return padded[0] # return the single sequence

# Get user input
user_input = input("Enter a sentence to analyze sentiment: ")

# Encode the user input
encoded_input = encode_text(user_input, imdb_word_index, maxlen=50)
# Reshape for the model input (batch size of 1)
encoded_input = np.expand_dims(encoded_input, axis=0)


# Predict sentiment
prediction = model.predict(encoded_input)

# Determine sentiment based on the sigmoid output
if prediction[0] > 0.5:
  sentiment = "Positive"
else:
  sentiment = "Negative"

print(f"The predicted sentiment for '{user_input}' is: {sentiment} (Confidence: {prediction[0][0]:.4f})")

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 1s 1us/step
Enter a sentence to analyze sentiment: I think movie was trahs
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 871ms/step
The predicted sentiment for 'I think movie was trahs' is: Negative (Confidence: 0.4774)


In [ ]:
# prompt: I want run this on streamlit

import streamlit as st
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten
from tensorflow.keras.datasets import imdb
import numpy as np
import os # Import the os module for saving/loading

# Function to build and potentially load the model
@st.cache_resource
def get_model():
    model_path = 'sentiment_rnn_model.h5'
    model = Sequential()
    model.add(Embedding(10000, 2))
    model.add(SimpleRNN(32, return_sequences=False))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

    # Check if the model exists and load it
    if os.path.exists(model_path):
        st.write("Loading pre-trained model...")
        model.load_weights(model_path)
    else:
        st.write("Training model (this may take a few minutes)...")
        # Load and preprocess data for training
        (X_train, y_train), (X_test, y_test) = imdb.load_data()
        X_train = pad_sequences(X_train, padding='post', maxlen=50)
        X_test = pad_sequences(X_test, padding='post', maxlen=50)
        # Train the model
        model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))
        # Save the trained model
        model.save_weights(model_path)
        st.write("Model trained and saved.")

    return model

# Load the IMDB word index
@st.cache_resource
def get_imdb_word_index():
  return imdb.get_word_index()

imdb_word_index = get_imdb_word_index()

# Function to encode text using the IMDB word index
def encode_text(text, word_index, maxlen=50):
  words = text.lower().split()
  # Handle potential KeyError by using .get and providing a default for unknown words (index 2 is unknown)
  encoded = [word_index.get(word, 2) + 3 for word in words] # +3 because 0, 1, 2 are reserved in IMDB data
  padded = pad_sequences([encoded], padding='post', maxlen=maxlen)
  return padded[0] # return the single sequence


# Get the model
model = get_model()

# Streamlit app
st.title("Sentiment Analysis with SimpleRNN")

st.write("Enter a sentence to predict its sentiment (Positive or Negative).")

user_input = st.text_area("Enter your sentence here:", "")

if st.button("Analyze Sentiment"):
    if user_input:
        # Encode the user input
        encoded_input = encode_text(user_input, imdb_word_index, maxlen=50)
        # Reshape for the model input (batch size of 1)
        encoded_input = np.expand_dims(encoded_input, axis=0)

        # Predict sentiment
        prediction = model.predict(encoded_input)

        # Determine sentiment based on the sigmoid output
        if prediction[0] > 0.5:
            sentiment = "Positive"
            st.success(f"Predicted Sentiment: **{sentiment}** (Confidence: {prediction[0][0]:.4f})")
        else:
            sentiment = "Negative"
            st.error(f"Predicted Sentiment: **{sentiment}** (Confidence: {prediction[0][0]:.4f})")
    else:
        st.warning("Please enter some text to analyze.")

# Instructions on how to run
st.markdown("""
To run this Streamlit app in Google Colab:

1.  Save the code above as a Python file (e.g., `app.py`).
2.  Install Streamlit and related libraries:
